# ÖRNEK — Gerçek sırları buraya DEĞİL secrets.toml dosyanıza yazın.
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "Edam456+"

TWILIO_ACCOUNT_SID = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"
ENABLE_AUTO_NOTIF = "true"
