
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "Edam456*"

TWILIO_ACCOUNT_SID = "ACafd4fb287f93c8d0f15c194156765894"
TWILIO_AUTH_TOKEN = "ce7e2e75f0a5dd63f0d817cbdd0b9053"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"
WEBHOOK_HOST = "http://127.0.0.1:8000"
